### PR TITLE
Implementing tests for the methods

### PR DESCRIPTION
**Pull request by ermin-cahtarevic**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
#### Pull request under review by Addo

**Review by Forison — APPROVED** [review]
# Hi @Ermin🙂.
It is a yes👌 from me.
Go ahead and merge to master.
## Project is approved💪
#### Happy coding
#### @Forison

**Comment by Forison** [comment]
Hi @ermin,
I am a bit curious was the project a solo project or a collaborative one?

**Comment by ermin-cahtarevic** [comment]
It was a collaborative project.

**Comment by Forison** [comment]
ok

**Pull request merged**
